# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_remove_patient_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='fname',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
