# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_auto_20170718_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='full_name',
            new_name='user_name',
        ),
    ]
