# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_auto_20170720_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='possible_disease',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
