# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-23 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0006_auto_20170723_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=1)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('Contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='disease',
            name='disease_description',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='disease_ref',
        ),
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checker.Symptom'),
        ),
    ]
