# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-25 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0007_auto_20170723_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Gender',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Specialization',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
