# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-31 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0009_auto_20170725_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='specialists',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
