# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-31 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0010_disease_specialists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='specialists',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
