# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-05 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0011_auto_20170731_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
    ]
